### ISSUE TITLE
Black Screen issue

### ISSUE THREAD

**Issue by vit-ndpm** [laravel-filament/filament#15191]
### Package

filament/filament

### Package Version

3.2.57

### Laravel Version

11.39

### Livewire Version

3.5

### PHP Version

8.2

### Problem description

I am using Laravel Filament v3 and encountered an issue when generating a resource. I generated the resource using the following command: php artisan make:filament-resource Player --generate

The resource generation completed successfully, but I am experiencing strange behavior in the table view of the generated resource. Specifically:

When I perform a search, apply a filter, change the number of items displayed, or navigate to another page in the table, a black screen modal immediately appears.
To view the updated data (e.g., navigating to page 2), I have to manually reload the page. After reloading, the table correctly shows the intended data (e.g., page 2).
I didn’t modify anything from the default generated resource Environment Details:

Laravel version: 11.39

Filament version: v3.2.57
Livewire version: 3.5

PHP version: 8.2

Browser: Chrome

### Expected behavior

On filter selection instead of black screen filtered results must show
In clicking item per page page must load with relevant items instead of black screen 

### Steps to reproduce

Identify the root cause and tell how to resolve this issue

### Reproduction repository (issue will be closed if this is not valid)

Player-Narmadapuram

### Relevant log output

```shell
Black screen
```

**Comment by vit-ndpm** [comment]
> Hey @vit-ndpm! We're sorry to hear that you've hit this issue. 💛
> 
> However, it looks like you forgot to fill in the reproduction repository URL. Can you edit your original post and then we'll look at your issue?
> 
> We need a public GitHub repository which contains a Laravel app with the minimal amount of Filament code to reproduce the problem. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private / confidential, since we want a link to a separate, isolated reproduction. That would allow us to download it and review your bug much easier, so it can be fixed quicker. Please make sure to include a database seeder with everything we need to set the app up quickly.

https://github.com/vit-ndpm/Players-Narmadapuram.git

**Comment by vit-ndpm** [comment]
> Hey @vit-ndpm! We're sorry to hear that you've hit this issue. 💛
> 
> 
> However, it looks like you forgot to fill in the reproduction repository URL. Can you edit your original post and then we'll look at your issue?
> 
> We need a public GitHub repository which contains a Laravel app with the minimal amount of Filament code to reproduce the problem. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private / confidential, since we want a link to a separate, isolated reproduction. That would allow us to download it and review your bug much easier, so it can be fixed quicker. Please make sure to include a database seeder with everything we need to set the app up quickly.
https://github.com/vit-ndpm/Players-Narmadapuram.git

**Comment by jgmuchiri** [comment]
@vit-ndpm Did you ever resolved this issue? I'm encountering the same on laravel 12 with filamentphp 3.3 and livewire 3.6.

Looks like a whole bunch of forms overlay the page when you perform those actions.

![Image](https://github.com/user-attachments/assets/fabf755f-3933-4509-959d-7945fdb09093)

**Comment by jgmuchiri** [comment]
My workaround for now is by hiding action modals in the theme css and implementing the actions in individual records.

```css
form[wire\:submit\.prevent="callMountedInfolistAction"] {
    display: none !important;
}
form[wire\:submit\.prevent="callMountedTableAction"] {
    display: none !important;
}
form[wire\:submit\.prevent="callMountedAction"] {
    display: none !important;
}
form[wire\:submit\.prevent="callMountedFormComponentAction"] {
    display: none !important;
}
form[wire\:submit\.prevent="callMountedTableBulkAction"] {
    display: none !important;
}
form[wire\:submit\.prevent="callMountedAction"] {
    display: none !important;
}
```
