### ISSUE TITLE
Livewire v3.5.17 breaks Filament's modal overlays' cloak behavior after any action in the Panel

### ISSUE THREAD

**Issue by E4SdJG528X9FsnpaBz6yxw** [laravel-filament/filament#15285]
### Package

filament/support

### Package Version

v3.2.124

### Laravel Version

v11.32.0

### Livewire Version

v3.5.17

### PHP Version

PHP 8.3.13

### Problem description

After composer update and `livewire/livewire` version changing from v3.4.12 to v3.5.17 the Panel's action started showing modal overlays (cloak issue?) blocking the whole screen. 

### Expected behavior

No modals or modal overlays are shown. 

### Steps to reproduce

1. Clone the repo.
2. Run docker-compose run --rm app composer install and then docker-compose run --rm app composer run prepare to init project. Port 8000 is used.
3. Go to http://localhost:8000/admin/users - use email / password - test@example.com / test@example.com
4. Click on the User's table to sort or input anything in the search field -- you should see that all model overlays are now visible.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/olexoliinyk0/filament-livewire-cloak-issue

**Comment by danharrin** [comment]
The latest versions of Filament in the last few weeks block Livewire higher than 3.5.12 from being installed, you might have upgraded or installed Livewire before then.

**Comment by jgmuchiri** [comment]
Experiencing this issue.

I'm having to manually hide modals using CSSS and implement custom actions 

```css

form[wire\:submit\.prevent="callMountedInfolistAction"] {
    display: none !important;
}
form[wire\:submit\.prevent="callMountedTableAction"] {
    display: none !important;
}
form[wire\:submit\.prevent="callMountedAction"] {
    display: none !important;
}
form[wire\:submit\.prevent="callMountedFormComponentAction"] {
    display: none !important;
}
form[wire\:submit\.prevent="callMountedTableBulkAction"] {
    display: none !important;
}
form[wire\:submit\.prevent="callMountedAction"] {
    display: none !important;
}
```
