### ISSUE TITLE
CSS :not() Selector Bug: Section contained(false) Still Receives Contained Styles

### ISSUE THREAD

**Issue by andrewdwallo** [laravel-filament/filament#16531]
### Package

filament/filament

### Package Version

v4.0.0-beta4

### Laravel Version

v11.45.1

### Livewire Version

v3.6.3

### PHP Version

PHP 8.2

## Bug Description

When using `Section::make()->contained(false)`, the section header and body receives padding from CSS rules that should be excluded by `:not(.fi-section-not-contained)` selectors.

## Reproduction Repository

**Repo**: https://github.com/andrewdwallo/erpsaas/tree/4.x

### To see the bug
Go to ClientResource.php and for the Primary Contact section:

1. Use `Section::make()->contained(false)` - header has unwanted padding (current code)
2. Switch to `CustomSection::make()->contained(false)` - header works correctly

Both components use **identical Blade templates and CSS logic**, but only Filament's Section is broken.

## Expected vs Actual

**Expected**: Sections with `contained(false)` should not receive padding from:
```css
.fi-section:not(.fi-section-not-contained):not(.fi-aside) .fi-section-header {
    padding-inline: calc(var(--spacing)*6);
    padding-block: calc(var(--spacing)*4);
}
```

<img width="1633" alt="Image" src="https://github.com/user-attachments/assets/3d9508df-0997-4380-b799-035d6b592d9c" />

**Actual**: The CSS rule applies despite element having `fi-section-not-contained` class.

<img width="1633" alt="Image" src="https://github.com/user-attachments/assets/54d49071-dd0d-4fe2-9609-c53648c8bedb" />

## Code Example

```php
Section::make('Primary Contact')
    ->contained(false)
    ->schema(...)
```

**HTML Output** (correct):
```html
<section class="fi-section fi-section-not-contained fi-section-has-header">
    <header class="fi-section-header"><!-- unwanted padding applied --></header>
</section>
```

## Proof It's a Filament CSS Bug

1. **Manual DevTools test**: Can toggle the problematic rule on/off
2. **Cross-browser**: Same issue in Chrome, Firefox, Safari, Edge  
3. **CSS logic test**: Copied exact same CSS with renamed classes (`fi-custom-section`) - works perfectly
4. **Component comparison**: Identical Blade templates - only css class names differ

### Expected behavior

Sections with `contained(false)` should not receive padding from:
```css
.fi-section:not(.fi-section-not-contained):not(.fi-aside) .fi-section-header {
    padding-inline: calc(var(--spacing)*6);
    padding-block: calc(var(--spacing)*4);
}
```
### Steps to reproduce

Go to ClientResource.php and for the Primary Contact section:

1. Use `Section::make()->contained(false)` - header has unwanted padding (current code)
2. Switch to `CustomSection::make()->contained(false)` - header works correctly

Both components use **identical Blade templates and CSS logic**, but only Filament's Section is broken.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/andrewdwallo/erpsaas/tree/4.x
