### ISSUE TITLE
Outline-color transition flash due to Tailwind 3.2.5

### ISSUE THREAD

**Issue by archilex** [laravel-filament/filament#5675]
### Package

filament/filament

### Package Version

v2.*

### Laravel Version

v.9

### PHP Version

8.1

### Problem description

Tailwind version 3.2.5, which released February 8, added the `outline-color` property to the `transition` and `transition-colors` utilities. [release notes](https://github.com/tailwindlabs/tailwindcss/blob/master/CHANGELOG.md)

This causes a weird flash when clicking into an input field as the outline is now being transitioned. 

Note: this only occurs if you've themed filament (ie. changed the colors) as the default config is still using 3.2.4. 

A few ways this can be fixed until/if this is updated is:

1. Lock your tailwind version in package.json to 3.2.4, then npm update. 
2. Or add the following to your `filament.css` file

```css
@layer components {
    .transition {
        transition-property: color,background-color,border-color,text-decoration-color,fill,stroke,opacity,box-shadow,transform,filter,backdrop-filter,-webkit-backdrop-filter !important
    }
}
```

### Expected behavior

The input fields shouldn't flash an outline color.

### Steps to reproduce

1. Follow the documentation to theme filament. Following the documention you'll pull in your version of tailwind instead of the filament's, which as of February 8 is 3.2.6. 
2. Open your browser and click into an input field to see the outline-color transition.

### Reproduction repository

https://github.com/archilex/filament-demo/tree/outline-color-bug
